apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Values.registry.secretName }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
type: Opaque
data:
  {{ .Values.registry.storageKey }}: {{ include "registrySecret" . | b64enc }}
  gcs.json: {{ .Values.registry.storageServiceAccountKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Values.storage.secretName }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
type: Opaque
data:
  {{ .Values.storage.connectionKey }}: {{ include "storageSecret" . | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Values.s3cmd.secretName }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
type: Opaque
data:
  {{ .Values.s3cmd.configKey }}: {{ include "s3cmdSecret" . | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Values.database.secretName }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
type: Opaque
data:
  {{ .Values.database.passwordKey }}: {{ .Values.database.password | b64enc }}